### ISSUE TITLE
Excluded Project

### ISSUE THREAD

**Issue by Gupta-Nikhil85** [SR-Sunny-Raj/Hacktoberfest2021-DSA#620]
On the hacktoberfest's website, the project is shown as excluded project.
Please look into the matter....

**Comment by SR-Sunny-Raj** [comment]
> On the hacktoberfest's website, the project is shown as excluded project. Please look into the matter....

Yes that's because of spamming pull request on this repo hacktoberfest team marked this project as excluded and they are doing this with every second project over github. Hope it will be included once again and as of now I can't do anything into this matter.  Request you to make your valid PR into some other project to make it count in the hacktoberfest.👍🏻

**Comment by Shubhambawner** [comment]
> On the hacktoberfest's website, the project is shown as excluded project. Please look into the matter....

link de do yrr ye website ki
