### ISSUE TITLE
Hacktoberfest- Project Excluded? 

### ISSUE THREAD

**Issue by whynesspower** [SR-Sunny-Raj/Hacktoberfest2021-DSA#798]
![image](https://user-images.githubusercontent.com/77494053/136276241-f1687de2-b0ae-488a-81b5-9ffa7aa73478.png)

@SR-Sunny-Raj is there anything we can do about it? This was a wonderful project, I was thinking of contributing more to it

**Comment by SR-Sunny-Raj** [comment]
> ![image](https://user-images.githubusercontent.com/77494053/136276241-f1687de2-b0ae-488a-81b5-9ffa7aa73478.png)
> 
> @SR-Sunny-Raj is there anything we can do about it? This was a wonderful project, I was thinking of contributing more to it

Hey @whynesspower, Yes this project has been marked as excluded because of spamming pull requests and hacktoberfest team is doing this with every other projects. Sadly we can't do anything in this case. But anyways it's all about open source contribution and we have already got a great project on DSA. You can freely contribute as many PR as you want.
